export interface Guest {
    id?: number; // Optional as it is generated by the backend
    name: string;
    email: string;
    diet: Diet;
    rsvpStatus: Rsvp;
  }

  export enum Diet {
    VEG = 'VEG',
    NON_VEG = 'NON_VEG',
  }

  export enum Rsvp {
    REGISTERED = 'REGISTERED',
    DECLINED = 'DECLINED',
    NO_RESPONSE = 'NO_RESPONSE',
  }
  