export interface Task {
    id?: number; // Optional as it is generated by the backend
    eventId: number; // Links the task to an event
    name: string;
    description: string;
    status: Status; // Enum for task status
    deadline: string; // Use string for compatibility with ISO date format
  }

  export enum Status {
    PENDING = 'PENDING',
    IN_PROGRESS = 'IN_PROGRESS',
    COMPLETED = 'COMPLETED',
  }
  