export interface Vendor {
    vendorId?: number; // Optional as it is generated by the backend
    vendorCompanyName: string;
    vendorServiceType: string;
    vendorName: string;
    vendorPhone: string;
    vendorEmail: string;
    vendorAmount: number;
  }

